apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ex-2
  labels:
    app: istio-ex-2
    version: v1
spec:
  selector:
    matchLabels:
      app: istio-ex-2
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-ex-2
        version: v1
    spec:
      containers:
        - name: master
          image: istio-ex-2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8081